### ISSUE TITLE
Update documentation about seeing templates

### ISSUE THREAD

**Issue by elinw** [seankross/postcards#1]
Hi,

This is really neat.

Edited
I didn't see the templates in my list but then I realized I needed to start a new session, so maybe add that to the instructions. 
I also wanted to suggest something that I've been doing with templates lately which is making a function like `assignment1()`  that opens up the file. Though they have worked with the FIle, RMarkdown, New, From Template it's always clunky and people on macs and Windows get them sorted differently so my demo doesn't look right to everyone.

**Comment by seankross** [comment]
Hi Elin,

Thank you so much for demoing this package. I uninstalled postcards, restarted R, and the templates did not appear in the template list. Then reinstalled postcards and the templates showed up in the template list, so I don't know why the templates are not showing up for you. 

Adding a `postcards_write()` function is a good idea to wrap `file.edit(rmarkdown::draft("index.Rmd", "Jolla", package = "postcards", edit = FALSE))`.

**Comment by elinw** [comment]
I updated the message, I started a new session  and they were there. I believe I may have run into that issue before.

**Comment by seankross** [comment]
According to [the R Markdown website](https://rstudio.github.io/rstudio-extensions/rmarkdown_templates.html) the right way to use the template without navigating around R Studio is: `rmarkdown::draft("index.Rmd", "Jolla", package = "postcards")` so I will add that to the documentation.
