### ISSUE TITLE
How to deploy postcard-webpage to Github Pages

### ISSUE THREAD

**Issue by joshua-persi** [seankross/postcards#13]
Hi, love the package! I'm having trouble deploying my postcard webpage through GitHub pages. It's not clear to me how I upload my .HTML or .Rmd file (_e_._g_. do I simply add the appropriate file to my repository or do I need to somehow replace the HTML code autogenerated by GitHub pages?). 

I looked at the GitHub Pages documentation but still couldn't figure it out. Any help would be greatly appreciated!

**Comment by ahcyip** [comment]
I believe the missing instruction is "rename your  knitted html file index.html in your abc.github.io directory"

**Comment by joshua-persi** [comment]
That fixed it! Thanks @ahcyip!

**Comment by ahcyip** [comment]
@seankross I didn't see it in the help/documentation either and I only knew to rename it index.html from old HTML/Geocities experience :) Has it been added?

**Comment by ahcyip** [comment]
I added a suggested instruction on the readme here: https://github.com/seankross/postcards/pull/15

**Comment by ahcyip** [comment]
> Hi, love the package! I'm having trouble deploying my postcard webpage through GitHub pages. It's not clear to me how I upload my .HTML or .Rmd file (_e_._g_. do I simply add the appropriate file to my repository or do I need to somehow replace the HTML code autogenerated by GitHub pages?).
> 
> I looked at the GitHub Pages documentation but still couldn't figure it out. Any help would be greatly appreciated!

Just a note: I checked the instructions on pages.github.io again and one of the steps does say:

Create an index file
Grab your favorite text editor and add an index.html file to your project:

So the complete instructions from template -> html creation -> user.github.io are all there :)
