### ISSUE TITLE
Regenerate previews (once relatively stable?)

### ISSUE THREAD

**Issue by ahcyip** [seankross/postcards#16]
Just a reminder - not a big deal. Thanks for making these templates! Brings me back to the days of Geocities...

**Comment by seankross** [comment]
Can you be more specific? I am not sure what you are asking.

**Comment by ahcyip** [comment]
I was referring to these preview pictures https://github.com/seankross/postcards/raw/main/man/figures/trestles-preview.png
after future (major?) changes. May not be that important, sorry!

**Comment by seankross** [comment]
No need to apologize, I really appreciate all of your interest in this package. As far as I can tell all of the recent changes to this package have not impacted how the pages themselves look. Do you think they have changed? It is possible that I changed something and I didn't notice.

**Comment by ahcyip** [comment]
agreed, the looks are still the same
