### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by shirdekel** [seankross/postcards#2]
Great package!

Small typo. You say to run: `rmarkdown::render("index.html")`, but I think you mean `rmarkdown::render("index.Rmd")`

**Comment by seankross** [comment]
Thank you for pointing this out, just fixed in 609e610
.

**Comment by ahcyip** [comment]
since this assumes the user named their file index.Rmd, I've added it as a suggestion in the readme instructions: https://github.com/seankross/postcards/pull/15
