### ISSUE TITLE
rMarkdown error with html self_contained

### ISSUE THREAD

**Issue by jfsavardenap** [seankross/postcards#22]
I installed your package from github both on Windows 10 and MacOS and I use RStudio. I made sure that all the dependencies are updated and that I have the latest version of pandoc on both computers. I use your default script for each theme and although the theme Jola knit well, I get the following error when trying to knit the default script for the other themes. I tried to fix it, but could not find what is wrong. Thank you in advance for your comments.

Error in rmarkdown::html_document(theme = NULL, self_contained = self_contained,  : 
 argument "css" is missing with no default value
Calls: <Anonymous> ... do.call -> <Anonymous> -> get_template -> <Anonymous>

**Comment by seankross** [comment]
The `main` branch of this package on GitHub is not stable. If you want to install a stable version of this package from GitHub you can with this command:

``` r
remotes::install_github("seankross/postcards@0.1.0")
```
